# Use Python 3.10
FROM python:3.10-slim

WORKDIR /app

# Copy files
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port
EXPOSE 3000

# Start server
CMD ["gunicorn", "--bind", "0.0.0.0:3000", "main:app"]
