# Use official lightweight Python image
FROM python:3.11-slim

# set workdir
WORKDIR /app

# avoid writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install system deps for reportlab (fonts, build deps)
RUN apt-get update && apt-get install -y build-essential libfreetype6-dev libjpeg-dev && rm -rf /var/lib/apt/lists/*

# copy requirements first to leverage Docker cache
COPY requirements.txt .

# install python deps
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# copy project
COPY . .

# expose port used by flask
EXPOSE 3000

# default start command
CMD ["python", "main.py"]
